# ===========
# CONFIG FILE
# ===========
#
# method
method: no-da  # no-da, mmd, dat, ynet, wnet or unet-ts
lambda_mmd: 1
lambda_dat: 1
lambda_rec: 1
lambda_o: 1
lambda_w: 1
# data
src:
  data: /home/jorisro/research/data/EM/EPFL/raw
  labels: /home/jorisro/research/data/EM/EPFL/labels
  train_val_split: 0.50
  split_orientation: z
tar:
  data: /home/j