# ===========
# CONFIG FILE
# ===========
#
# method
method: u-net  # u-net
# data
data: /home/jorisro/research/data/EM/VNC/raw
labels: /home/jorisro/research/data/EM/VNC/labels
train_val_test_split: 0.50,0.75
split_orientation: z
type: pngseq
augmentation: rot90,flipx,flipy,contrast,deformation,noise  # options: rot90,flipx,flipy,contrast,deformation,noise
# network
input_size: 256,256
in_channels: 1
fm: 16
levels: 4
dropout: 0.00
norm: batch
activation: relu
coi: 0,1
# 